apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: web-server
  namespace: it-team
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "256Mi"
            cpu: "900m"
          limits:                         # This is to define the Limit (Upper Limit)
            memory: "512Mi"
            cpu: "1200m"
